---
  - name: Install Kubernetes
    hosts: kubemaster
    become: yes
    roles:
      - prepare_host
      - kubernetes
    tasks:
      - name: Initializing master
        shell: kubeadm init --api-advertise-addresses={{ ansible_default_ipv4.address }} --pod-network-cidr={{ network.pod_network_cidr }} --service-cidr={{ network.svc_network_cidr }}  --service-dns-domain={{ svc_dns_domain }} --token={{ token }}
        register: result

      - debug: var=result.stdout

      - name: Generate network yaml
        template: src=../templates/kube-flannel.yml dest=/tmp/network.yml

      - name: Install Network pod
        shell: kubectl apply -f /tmp/network.yml

      - name: Wait for setup networking
        pause: seconds=60 

  - name: Install Kubernetes
    hosts: kubeminion
    serial: 1
    become: yes
    roles:
      - prepare_host
      - kubernetes
    tasks:
      - name: Join master
        shell: kubeadm join --token={{ token }} "{{ hostvars['kubemaster1']['ansible_host'] }}"

      - name: Wait for setup networking
        pause: seconds=10 
