---
  - name: Add kubernetes APT Key
    apt_key: url=https://packages.cloud.google.com/apt/doc/apt-key.gpg validate_certs=no state=present

  - name: Add kubernetes Repository
    apt_repository: repo="deb http://apt.kubernetes.io/ kubernetes-xenial main" state=present

  - name: Install kubernetes and docker
    apt: name={{ item }} state=present update_cache=true
    with_items:
      - kubelet
      - kubeadm
      - kubectl
      - kubernetes-cni
      - docker.io

  - name: Update /etc/default/docker
    lineinfile: dest=/etc/default/docker  line="DOCKER_OPTS=\"--insecure-registry {{ docker.registry }}\"" state=present
    when: not docker.registry_secure

  - name: restart docker
    service: name=docker state=restarted
